# Generated by Django 3.2.4 on 2021-06-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0002_task2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task2',
            name='Mobile',
            field=models.CharField(max_length=100),
        ),
    ]
